### PR TITLE
rework 3.14 and Additional Content

### PR DESCRIPTION
**Pull request by andreadavanzo**
I upgrade the "mobile first" to "Device-Adaptable". This because I found several websites that are only "mobile-first", other that are mobile and desktop, but terrible on big screens like smart tv.
Given the option to use one or more approaches for implementing Device-Adaptable solution keeping in mind their sustainability.
Suggested a new description of Additional Content Benefits > Environmental:

### CODE REVIEW

**Comment by andreadavanzo** [comment]
I upgrade the "mobile first" to "Device-Adaptable". This because I found several websites that are only "mobile-first", other that are mobile and desktop, but terrible on big screens like smart tv.
Given the option to use one or more approaches for implementing Device-Adaptable solution keeping in mind their sustainability.
Suggested a new description of Additional Content Benefits > Environmental:

**Comment by andreadavanzo** [comment]
I upgrade the "mobile first" to "Device-Adaptable". This because I found several websites that are only "mobile-first", other that are mobile and desktop, but terrible on big screens like smart tv.
Given the option to use one or more approaches for implementing Device-Adaptable solution keeping in mind their sustainability.
Suggested a new description of Additional Content Benefits > Environmental:

**Comment by andreadavanzo** [comment]
got an error

**Comment by andreadavanzo** [comment]
I upgrade the "mobile first" to "Device-Adaptable". This because I found several websites that are only "mobile-first", other that are mobile and desktop, but terrible on big screens like smart tv.
Given the option to use one or more approaches for implementing Device-Adaptable solution keeping in mind their sustainability.
Suggested a new description of Additional Content Benefits > Environmental:

**Comment by andreadavanzo** [comment]
I upgrade the "mobile first" to "Device-Adaptable". This because I found several websites that are only "mobile-first", other that are mobile and desktop, but terrible on big screens like smart tv.
Given the option to use one or more approaches for implementing Device-Adaptable solution keeping in mind their sustainability.
Suggested a new description of Additional Content Benefits > Environmental:

**Comment by AlexDawsonUK** [comment]
I totally agree with your suggestions. Thanks!

Post merging I'll also make necessary adjustments to supplements to ensure continuity.

**Comment by AlexDawsonUK** [comment]
Just a follow up to note that I've completed the editorial work with content alignment as required.

A couple of minor editorial changes were made to tidy the markup, resolve something that will be addressed in another issue, etc. The finished copy is in our [Living Draft](https://w3c.github.io/sustyweb/drafts/) and will be published with the next public draft release soon.

**Pull request merged**
